version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
    -  27017:27017
    networks:
     -  app-network
     
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - '3005:3004' 
    depends_on:
        - mongodb
    networks:
       - app-network
networks:
 app-network:

    

 